print("Enter the values of coeficient a, b , c of quadratic equation" "  ax^2+bx+c=0" )
print("a:")
a=int(input())
print("b:")
b=int(input())
print("c:")
c=int(input())
print("x1:")
x1=(-b+(b**2-4*a*c)**0.5)/(2*a)
print(x1)
print("x2:")
x2=(-b-(b**2-4*a*c)**0.5)/(2*a)
print(x2)